version: '3.8'

services:
  # 1. DATABASE
  postgres-db:
    image: postgres:15
    container_name: hotel_db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 2. BACKEND API
  hotel-backend:
    build: ./hotel_backend
    container_name: hotel_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # 3. FRONTEND (NGINX)
  hotel-frontend:
    build: ./hotel_frontend
    container_name: hotel_frontend
    ports:
      - "5173:80" 
    depends_on:
      - hotel-backend

volumes:
  db_data: